### ISSUE TITLE
Display second Compose in reports that are Updates or Upgrades

### ISSUE THREAD

**Issue by nathan-weinberg** [nathan-weinberg/jeeves#176]
This could be done by searching job name strings for keywords such as "update" and "upgrade" and "ffu" and then have `get_jenkins_job_info` pull data on the second compose from Jenkins

**Comment by itzikb** [comment]
+1
Should be looked at these words also in capitals and should be added to documentation.
It may be worth to have a second table for that.
I wonder what should be done regarding the presentation of the tests results

**Comment by EliadCohen** [comment]
The job names may change with time (There's already talk about this). I think this should be up to the user to mark which ones are upgrade/update.
Maybe specify a flag in the blockers file?

```
JOBS-team-upgrade-from-to-etc-etc-etc:
  bz:
    - 0
  extract_two_versions: true
  jira:
    - 0 
```
 

or such
